@startuml
scale 450 width
class Estudiante{
}
class colegio{
}
class matricula{
Nombre Alumno()
}
class profesor{
}
class seccion {
}
     'herencia
colegio <|-- seccion
     'Agregacion
seccion o-- profesor
seccion o-- Estudiante
     'Asociacion entre estudiante y seccion
Estudiante "0..*" - "1..*"seccion
     'Matricula relaciona estudiante y seccion
matricula .. estudiante
matricula .. seccion


@enduml